# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Clean build directory and re-build debug and test apks"
  lane :cleanAssembleDebugTest do
    gradle(
      task: 'clean'
    )
    gradle(
      task: 'assemble',
      build_type: 'Debug'
    )
    gradle(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  end

  desc "Build debug and test apks"
  lane :assembleDebugTest do
    gradle(
      task: 'assemble',
      build_type: 'Debug'
    )
    gradle(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  end

  desc "Run gradle lintDebug"
  lane :lint do
    gradle(
      task: 'lint',
      build_type: 'Debug'
    )
  end

  desc "Set version name in local.properties.sample using latest version listed in CHANGELOG.txt"
  lane :setVersionNameSample do
    ENV["VERSION_NAME"] = sh "head -1 metadata/android/en-US/changelogs/CHANGELOG.txt \
                                    | cut -d 'v' -f2 \
                                    | tr -d '\n'"
    sh "sed -i \"s/versionName=.*/versionName=${VERSION_NAME}/g\" ../local.properties.sample"
  end

  desc "Set version name in local.properties using latest version listed in CHANGELOG.txt"
  lane :setVersionName do
    ENV["VERSION_NAME"] = sh "head -1 metadata/android/en-US/changelogs/CHANGELOG.txt \
                                    | cut -d 'v' -f2 \
                                    | tr -d '\n'"
    sh "sed -i \"s/versionName=.*/versionName=${VERSION_NAME}/g\" ../local.properties"
  end

  desc "Clean build directory and re-build nightly apks and bundle"
  lane :cleanAssembleNightly do
    gradle(
      task: 'clean'
    )
    gradle(
      task: 'assemble',
      build_type: 'Nightly'
    )
    gradle(
      task: 'bundle',
      build_type: 'Nightly'
    )
  end

  desc "Clean build directory and re-build nightly apks and bundle"
  lane :cleanAssembleRelease do
    gradle(
      task: 'clean'
    )
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
  end

  desc "Create checksum of releases binaries"
  lane :checksumRelease do
    sh "sha256sum ../output/release/* > ../output/release/sha256sums.txt"
  end

  desc "Create release notes from CHANGELOG.txt to ${VERSION_CODE}.txt for nightly release"
  lane :createNightlyNotes do
    ENV["LOCAL_VERSION"] = sh " cat ../local.properties \
                                    | grep versionName \
                                    | cut -d '=' -f2"
    ENV["VERSION_NAME"] = sh "echo $([ -z $CENO_VERSION ] && echo $LOCAL_VERSION || echo $CENO_VERSION) | tr -d '\n'"
    ENV["VERSION_CODE"]  = sh "java -jar /opt/bundletool-all-1.17.1.jar dump manifest \
                                --bundle ../app/build/outputs/bundle/nightly/app-nightly.aab \
                                --xpath /manifest/@android:versionCode \
                                | tr -d '\n'"
    sh "sed -n \"/${VERSION_NAME}/,/#/p\" metadata/android/en-US/changelogs/CHANGELOG.txt \
        | head -n -2 \
        | tail -n +2 \
        > metadata/android/en-US/changelogs/${VERSION_CODE}.txt"
  end

  desc "Create and copy release notes from CHANGELOG.txt to ${VERSION_CODE}.txt for production release"
  lane :createReleaseNotes do
    ENV["LOCAL_VERSION"] = sh " cat ../local.properties \
                                    | grep versionName \
                                    | cut -d '=' -f2"
    ENV["VERSION_NAME"] = sh "echo $([ -z $CENO_VERSION ] && echo $LOCAL_VERSION || echo $CENO_VERSION) | tr -d '\n'"
    ENV["MAJOR"] = sh "printf %02d $(echo $VERSION_NAME | cut -d . -f 1)"
    ENV["MINOR"] = sh "printf %03d $(echo $VERSION_NAME | cut -d . -f 2)"
    ENV["PATCH"] = sh "printf %02d $(echo $VERSION_NAME | cut -d . -f 3)"
    # TODO: get revision number from local.properties if set
    #ENV["LOCAL_REVISION"] = sh " cat ../local.properties \
    #                                | grep revision \
    #                                | cut -d '=' -f2"
    ENV["REVISION"] = sh "echo '0' | tr -d '\n'"
    ENV["VERSION_CODE_0"] = sh "echo 2${MAJOR}${MINOR}${PATCH}0${REVISION} | tr -d '\n'"
    ENV["VERSION_CODE_1"] = sh "echo 2${MAJOR}${MINOR}${PATCH}1${REVISION} | tr -d '\n'"
    ENV["VERSION_CODE_2"] = sh "echo 2${MAJOR}${MINOR}${PATCH}2${REVISION} | tr -d '\n'"
    sh "sed -n \"/${VERSION_NAME}/,/#/p\" metadata/android/en-US/changelogs/CHANGELOG.txt \
        | head -n -2 \
        | tail -n +2 \
        > metadata/android/en-US/changelogs/${VERSION_CODE_0}.txt"
    # arm64-v8a version code
    sh "cp metadata/android/en-US/changelogs/${VERSION_CODE_0}.txt metadata/android/en-US/changelogs/${VERSION_CODE_1}.txt"
    # x86_64 version code
    sh "cp metadata/android/en-US/changelogs/${VERSION_CODE_0}.txt metadata/android/en-US/changelogs/${VERSION_CODE_2}.txt"
  end

  desc "Clean up repo after changes required for play store upload"
  lane :cleanRepo do
      sh "git restore ."
      sh "git clean -f"
      sh "git clean -fd"
  end

  lane :screenshots do |options|
    if options[:abi] == "" then
        apk_path = './app/build/outputs/apk/debug/app-arm64-v8a-debug.apk'
    else
        apk_path = './app/build/outputs/apk/debug/app-' + options[:abi] + '-debug.apk'
    end
    capture_android_screenshots(
        app_apk_path: apk_path
    )
  end

  desc "Run tasks if new commits have been made to develop"
  lane :nightly do
    previous_commit = last_git_commit[:commit_hash]
    sh "git pull origin develop"
    current_commit = last_git_commit[:commit_hash]
    if current_commit != previous_commit then
      setVersionName
      cleanAssembleDebugTest
      lint
      # Uploads debug apk to BrowserStack and starts tests
      sh "../start_testsuite.sh -u"

      # Make nightly builds and upload to Play Store internal test track
      cleanAssembleNightly
      createNightlyNotes
      # Rename pt to pt-PT, pt is created by weblate, but only pt-PT is supported by play store
      sh "mv metadata/android/pt metadata/android/pt-PT"
      upload_to_play_store(
        track: 'internal',
        release_status: 'completed',
        skip_upload_apk: 'true',
        skip_upload_metadata: 'true',
        skip_upload_changelogs: 'false',
        skip_upload_images: 'true',
        skip_upload_screenshots: 'true',
      )

      # Run localTests on all connected devices
      #adb_devices.each do |device|
      #  model = adb(command: "shell getprop ro.product.model",
      #    serial: device.serial).strip
      #  puts "Running test on #{model}"
      #  ENV['ANDROID_SERIAL'] = device.serial
      #  gradle(
      #    task: 'connectedDebugAndroidTest'
      #  )
      #end

      cleanRepo
    end
  end

  desc "Prepare release APKS, AAB, and release notes"
  lane :prepareRelease do
      setVersionName
      setVersionNameSample
      createReleaseNotes
  end

  desc "Build release APKS, AAB, write checksum"
  lane :buildRelease do
      lint
      cleanAssembleRelease
      checksumRelease
  end

  desc "Publish metadata and screenshots to Play Store"
  lane :publishMetadata do
    # Temporarily rename pt to pt-PT, only pt-PT is supported by play store
    sh "mv metadata/android/pt metadata/android/pt-PT"
    upload_to_play_store(
      skip_upload_apk: 'true',
      skip_upload_aab: 'true',
      skip_upload_metadata: 'false',
      skip_upload_changelogs: 'true',
      skip_upload_images: 'true',
      skip_upload_screenshots: 'false',
      sync_image_upload: 'true'
    )
    sh "mv metadata/android/pt-PT metadata/android/pt"
  end
end
